const crops = [{"seed_id":"01H7SSCWY5JP0WYVGR27H5XWTH","seed_name":"Jelly Lichen","seed_type":"Vegetable","seed_variety":"Corn","seed_price":23.56,"seed_quantity":0,"seed_origin":"Brazil","seed_harvest_date":"3/15/2022","seed_description":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.","seed_image_url":"avinash-kumar-OvUAL6Vx3uY-unsplash.jpg","seed_supplier":"Tremblay LLC"},
{"seed_id":"01H7SSCX690BM7N1MZDWTXKGS0","seed_name":"Birdwing Treefern","seed_type":"Grain","seed_variety":"Tomato","seed_price":34.51,"seed_quantity":661,"seed_origin":"China","seed_harvest_date":"10/30/2022","seed_description":"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.","seed_image_url":"dan-cristian-padure-TMBNssbpwRw-unsplash.jpg","seed_supplier":"Waters Inc"},
{"seed_id":"01H7SSCX6B74MNP4NTSR8FBD0C","seed_name":"Spatulaleaf Loosestrife","seed_type":"Grain","seed_variety":"Tomato","seed_price":71.22,"seed_quantity":30,"seed_origin":"New Zealand","seed_harvest_date":"10/25/2022","seed_description":"Fusce consequat. Nulla nisl. Nunc nisl.","seed_image_url":"goh-rhy-yan-hTd-y7MBrMg-unsplash.jpg","seed_supplier":"Gulgowski LLC"},
{"seed_id":"01H7SSCX6CZQEFR378D21NXW12","seed_name":"Peacocksplume","seed_type":"Grain","seed_variety":"Corn","seed_price":3.7,"seed_quantity":0,"seed_origin":"Poland","seed_harvest_date":"6/18/2022","seed_description":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.","seed_image_url":"avinash-kumar-OvUAL6Vx3uY-unsplash.jpg","seed_supplier":"Lehner-Maggio"},
{"seed_id":"01H7SSCX6E3DTVBHCS9J49SKP2","seed_name":"St. Anthony Dunes Evening Primrose","seed_type":"Vegetable","seed_variety":"Apple","seed_price":25.56,"seed_quantity":650,"seed_origin":"China","seed_harvest_date":"10/14/2022","seed_description":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.","seed_image_url":"pierre-bamin-dPJBDzb-NXw-unsplash.jpg","seed_supplier":"Orn-Kunze"},
{"seed_id":"01H7SSCX6FN6BV8PY2XVRDZM0R","seed_name":"Hoary Buckwheat","seed_type":"Grain","seed_variety":"Corn","seed_price":94.71,"seed_quantity":595,"seed_origin":"Czech Republic","seed_harvest_date":"2/23/2022","seed_description":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","seed_image_url":"dan-cristian-padure-TMBNssbpwRw-unsplash.jpg","seed_supplier":"Ortiz, Cremin and Renner"},
{"seed_id":"01H7SSCX6HP14HFB77P3SXYMHP","seed_name":"Preuss' Dioscorea","seed_type":"Grain","seed_variety":"Corn","seed_price":92.64,"seed_quantity":20,"seed_origin":"Peru","seed_harvest_date":"3/18/2022","seed_description":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.","seed_image_url":"joanna-kosinska-6MlhT-THmk4-unsplash.jpg","seed_supplier":"Emard, Dickens and Abshire"},
{"seed_id":"01H7SSCX6JM4QAFGP53K4M1Z7S","seed_name":"Sticky Whiteleaf Manzanita","seed_type":"Grain","seed_variety":"Wheat","seed_price":86.06,"seed_quantity":189,"seed_origin":"Russia","seed_harvest_date":"4/16/2022","seed_description":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.","seed_image_url":"dan-cristian-padure-TMBNssbpwRw-unsplash.jpg","seed_supplier":"Schultz Inc"},
{"seed_id":"01H7SSCX6MF5MDS7J5Q6NY5ZXG","seed_name":"Needlegrass","seed_type":"Grain","seed_variety":"Wheat","seed_price":54.85,"seed_quantity":895,"seed_origin":"China","seed_harvest_date":"2/3/2022","seed_description":"Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.","seed_image_url":"dan-cristian-padure-TMBNssbpwRw-unsplash.jpg","seed_supplier":"Shields, Abshire and Daniel"},
{"seed_id":"01H7SSCX6N06E6BTQT2M5DC1V5","seed_name":"Dwarf Naupaka","seed_type":"Vegetable","seed_variety":"Corn","seed_price":42.11,"seed_quantity":19,"seed_origin":"Macedonia","seed_harvest_date":"10/19/2022","seed_description":"In congue. Etiam justo. Etiam pretium iaculis justo.","seed_image_url":"wolfgang-hasselmann-nK1lc3qTpcI-unsplash.jpg","seed_supplier":"Grant and Sons"},
{"seed_id":"01H7SSCX6QAW5B58CKZNZDQYG8","seed_name":"Sonoran Indigo","seed_type":"Vegetable","seed_variety":"Apple","seed_price":0.91,"seed_quantity":276,"seed_origin":"Latvia","seed_harvest_date":"3/1/2022","seed_description":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","seed_image_url":"avinash-kumar-OvUAL6Vx3uY-unsplash.jpg","seed_supplier":"Corwin-Bayer"},
{"seed_id":"01H7SSCX6R78JD7EAPTSW6WN1A","seed_name":"Pacific Aster","seed_type":"Fruit","seed_variety":"Apple","seed_price":95.09,"seed_quantity":149,"seed_origin":"Russia","seed_harvest_date":"2/11/2022","seed_description":"Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.","seed_image_url":"pierre-bamin-dPJBDzb-NXw-unsplash.jpg","seed_supplier":"Welch, Gerlach and Johns"},
{"seed_id":"01H7SSCX6TR0KXHDGQDZCQ28D9","seed_name":"Sagiolechia Lichen","seed_type":"Grain","seed_variety":"Corn","seed_price":12.09,"seed_quantity":161,"seed_origin":"Philippines","seed_harvest_date":"7/22/2022","seed_description":"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.","seed_image_url":"dan-cristian-padure-TMBNssbpwRw-unsplash.jpg","seed_supplier":"Koch, Kuphal and Kertzmann"},
{"seed_id":"01H7SSCX6W5V3WMFGG7DBCE407","seed_name":"Ashby's Banksia","seed_type":"Grain","seed_variety":"Corn","seed_price":64.92,"seed_quantity":992,"seed_origin":"France","seed_harvest_date":"9/13/2022","seed_description":"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.","seed_image_url":"pierre-bamin-dPJBDzb-NXw-unsplash.jpg","seed_supplier":"Stanton Group"},
{"seed_id":"01H7SSCX6Z95DQYG6Y8EWPBNQN","seed_name":"Fourpart Dwarf Gentian","seed_type":"Grain","seed_variety":"Tomato","seed_price":87.73,"seed_quantity":851,"seed_origin":"France","seed_harvest_date":"11/14/2022","seed_description":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.","seed_image_url":"goh-rhy-yan-hTd-y7MBrMg-unsplash.jpg","seed_supplier":"Walter LLC"},
{"seed_id":"01H7SSCX72Z6A3M5X67C2XG11Z","seed_name":"Pygmy Date Palm","seed_type":"Vegetable","seed_variety":"Tomato","seed_price":0.57,"seed_quantity":363,"seed_origin":"Japan","seed_harvest_date":"1/11/2022","seed_description":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.","seed_image_url":"goh-rhy-yan-hTd-y7MBrMg-unsplash.jpg","seed_supplier":"Barrows LLC"},
{"seed_id":"01H7SSCX75KFQE1P5JDWFAV8RF","seed_name":"Cold Crabseye Lichen","seed_type":"Vegetable","seed_variety":"Tomato","seed_price":44.13,"seed_quantity":862,"seed_origin":"China","seed_harvest_date":"5/1/2022","seed_description":"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.","seed_image_url":"goh-rhy-yan-hTd-y7MBrMg-unsplash.jpg","seed_supplier":"Thompson-Casper"},
{"seed_id":"01H7SSCX77BTQWC3P4SHD7YTPN","seed_name":"Limestone Grass","seed_type":"Vegetable","seed_variety":"Wheat","seed_price":80.13,"seed_quantity":831,"seed_origin":"Uganda","seed_harvest_date":"7/8/2022","seed_description":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.","seed_image_url":"avinash-kumar-OvUAL6Vx3uY-unsplash.jpg","seed_supplier":"Friesen, Becker and Stracke"},
{"seed_id":"01H7SSCX78SN00BF9KPCTZ9WMS","seed_name":"Jerusalem Artichoke","seed_type":"Fruit","seed_variety":"Tomato","seed_price":72.0,"seed_quantity":206,"seed_origin":"Mexico","seed_harvest_date":"12/16/2022","seed_description":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","seed_image_url":"goh-rhy-yan-hTd-y7MBrMg-unsplash.jpg","seed_supplier":"Bayer, Abbott and Fahey"},
{"seed_id":"01H7SSCX7A2ZP2HEZQHHZ07EG0","seed_name":"Barbara's Buttons","seed_type":"Grain","seed_variety":"Corn","seed_price":35.61,"seed_quantity":104,"seed_origin":"Brazil","seed_harvest_date":"3/3/2022","seed_description":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.","seed_image_url":"avinash-kumar-OvUAL6Vx3uY-unsplash.jpg","seed_supplier":"Grant-Parker"},
{"seed_id":"01H7SSCX7B1SEVT2YFKB4WNZSJ","seed_name":"Prickly Hawkweed","seed_type":"Fruit","seed_variety":"Wheat","seed_price":92.86,"seed_quantity":760,"seed_origin":"China","seed_harvest_date":"9/24/2022","seed_description":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.","seed_image_url":"joanna-kosinska-6MlhT-THmk4-unsplash.jpg","seed_supplier":"O'Kon, Swaniawski and Bartell"},
{"seed_id":"01H7SSCX7CFDR2W9XGCKYRSYCZ","seed_name":"Black Grama","seed_type":"Grain","seed_variety":"Tomato","seed_price":32.95,"seed_quantity":747,"seed_origin":"Sri Lanka","seed_harvest_date":"10/4/2022","seed_description":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","seed_image_url":"avinash-kumar-OvUAL6Vx3uY-unsplash.jpg","seed_supplier":"Bechtelar, McClure and Mann"},
{"seed_id":"01H7SSCX7E62CGS0F15JB8GHYE","seed_name":"Polyalthia","seed_type":"Grain","seed_variety":"Wheat","seed_price":41.87,"seed_quantity":809,"seed_origin":"Belarus","seed_harvest_date":"3/16/2022","seed_description":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","seed_image_url":"wolfgang-hasselmann-nK1lc3qTpcI-unsplash.jpg","seed_supplier":"Stoltenberg Group"},
{"seed_id":"01H7SSCX7FAGFTP1RJDR9T3YNQ","seed_name":"Anthracothecium Lichen","seed_type":"Grain","seed_variety":"Apple","seed_price":33.18,"seed_quantity":348,"seed_origin":"China","seed_harvest_date":"6/8/2022","seed_description":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.","seed_image_url":"pierre-bamin-dPJBDzb-NXw-unsplash.jpg","seed_supplier":"Ernser LLC"}]


module.exports = {
    crops
  }